//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.BooksOwneds = new HashSet<BooksOwned>();
        }
    
        public int TransactionID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> UserID_from { get; set; }
        public Nullable<int> UserID_to { get; set; }
        public Nullable<System.DateTime> Date_transaction { get; set; }
        public Nullable<System.DateTime> Date_penalty { get; set; }
    
        public virtual Book Book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BooksOwned> BooksOwneds { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
