<?xml version="1.0" encoding="utf-8"?><Database Name="UncensoredLibrary" Class="UncensoredLibraryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=UncensoredLibrary;Integrated Security=True" SettingsObjectName="LibraryManagementSystem.Properties.Settings" SettingsPropertyName="UncensoredLibraryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Accounts" Member="Accounts">
    <Type Name="Account">
      <Column Name="AccountID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Association Name="User_Account" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Books" Member="Books">
    <Type Name="Book">
      <Column Name="BookID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MinAge" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NChar(128)" CanBeNull="true" />
      <Association Name="Book_Transaction" Member="Transactions" ThisKey="BookID" OtherKey="BookID" Type="Transaction" />
    </Type>
  </Table>
  <Table Name="dbo.Transactions" Member="Transactions">
    <Type Name="Transaction">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BookID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID_from" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID_to" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date_transaction" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Date_penalty" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Book_Transaction" Member="Book" ThisKey="BookID" OtherKey="BookID" Type="Book" IsForeignKey="true" />
      <Association Name="User_Transaction" Member="User" ThisKey="UserID_from" OtherKey="UserID" Type="User" IsForeignKey="true" />
      <Association Name="User_Transaction1" Member="User1" ThisKey="UserID_to" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Role" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateRegistered" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FirstBookDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LastBookDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ProfilePicture" Type="System.String" DbType="NChar(128)" CanBeNull="true" />
      <Association Name="User_Account" Member="Accounts" ThisKey="UserID" OtherKey="UserID" Type="Account" />
      <Association Name="User_Transaction" Member="Transactions" ThisKey="UserID" OtherKey="UserID_from" Type="Transaction" />
      <Association Name="User_Transaction1" Member="Transactions1" ThisKey="UserID" OtherKey="UserID_to" Type="Transaction" />
    </Type>
  </Table>
</Database>